// <auto-generated />
namespace FitnessDietApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_in_context : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_in_context));
        
        string IMigrationMetadata.Id
        {
            get { return "201612101253225_Change_in_context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
